name: Sync OAS to ReadMe OnStock
on:
  push:
    branches:
      - master
      - main
jobs:

  build2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readmeio/github-readme-sync@v2
        with:
          readme-oas-key: UvAWPMGDFa44GR7A0SHWJiu9EtosRkq3:61af6703db4473fe20085f17
          # OPTIONAL CONFIG, use if necessary
          oas-file-path: './onstock/openapi.yaml'
          api-version: 'v1.0.0'
