name: Sync OAS to ReadMe OnStock
on:
  push:
    branches:
      - master
      - main
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: readmeio/rdme@8.6.6
        with:
          rdme: openapi ./onstock/openapi.yaml --key=${{secrets.README_OAS_KEY}} --id=61af6819429f960f63440868
